# Generated by Django 2.1.3 on 2019-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pronto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronto_id', models.TextField()),
                ('release', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('build', models.TextField(blank=True, null=True)),
                ('severity', models.TextField(blank=True, null=True)),
                ('implementation_responsible_person', models.TextField(blank=True, max_length=50, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('transfer_from', models.TextField(blank=True, null=True)),
                ('transfer_to', models.TextField(blank=True, null=True)),
                ('rca_state', models.TextField(blank=True, null=True)),
                ('reported_date', models.DateTimeField(blank=True, null=True, verbose_name='Reported Date')),
                ('rft_date', models.DateTimeField(blank=True, null=True, verbose_name='RFT Date')),
                ('in_date', models.DateTimeField(blank=True, null=True, verbose_name='In Date')),
                ('out_date', models.DateTimeField(blank=True, null=True, verbose_name='Out Date')),
                ('root_cause_found_date', models.DateTimeField(blank=True, null=True, verbose_name='Root Cause Found Date')),
                ('is_top', models.TextField(blank=True, default='false', null=True)),
                ('group_idx', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
