# Generated by Django 2.1.3 on 2019-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronto',
            name='Feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
