# Generated by Django 2.1.3 on 2019-04-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronto', '0002_pronto_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pronto',
            old_name='Feature',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='pronto',
            old_name='implementation_responsible_person',
            new_name='responsible_person',
        ),
    ]
